import "./globals.css";
import styles from "./page.module.css";
import {textFont} from "./fonts";
import Navbar from "@/components/navigation/navbar";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

export const metadata = {
  title: "My Lore",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.png" type="image/png" sizes="32x32" />
      </head>
      <body className={textFont.className} suppressHydrationWarning={true}>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
